# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-json
    - id: detect-aws-credentials
    - id: end-of-file-fixer
    - id: pretty-format-json
    - id: trailing-whitespace
-  repo: https://github.com/pre-commit/mirrors-yapf
   rev: v0.32.0
   hooks:
   -    id: yapf
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17  # Use the ref you want to point at
  hooks:
  - id: mdformat
    # optional
    additional_dependencies:
    - mdformat-tables
    - mdformat-black
    - mdformat-beautysh
- repo: https://github.com/lovesegfault/beautysh.git
  rev: v6.2.1
  hooks:
  - id: beautysh
- repo: https://github.com/awslabs/cfn-python-lint
  rev: v0.79.9 # The version of cfn-lint to use
  hooks:
    - id: cfn-python-lint
      files: templates/.*\.(json|yml|yaml)$
